#!/system/bin/sh
exit
COMP JESUSGO O3 POLLY TLTO
# JESUS GO
LOAD CPPStartPoint,KTStartPoint
POT res
DEP CRYTO,DATA,KTO STRPOT
SRT FUN ATOPC
FIND HKP
SET HKP HKP
ATCG HKP HKPT
ATOP HKPT
SET HKPT HKP
HCP HKP HKP
RT0
END FUN ATOPC 
ORR POT ATOPC 
POT 
SRT ATOPT,SDNA,P2PDN,RMCT,OPHW,RCKL
FCK OKL,OD,RECS